import sqlite3

conn = sqlite3.connect('database.db')
# conn.execute('CREATE TABLE USERS (NAME TEXT,ID TEXT,EMAIL TEXT,PASSWORD TEXT,PHONE TEXT,TYPE TEXT)')
# conn.execute('CREATE TABLE WASTE (QUANTITY TEXT,FOOD TEXT,DATE TEXT)')
conn.execute('CREATE TABLE FEEDBACK (DATA TEXT)')